### PR TITLE
edit the style and added route functions

### PR DESCRIPTION
**Pull request by TylerSilverman**
edit the style and added route functions

### CODE REVIEW

**Comment by TylerSilverman** [comment]
edit the style and added route functions

**Review by simk2020 — COMMENTED** [review]
good

**Review by simk2020 — COMMENTED** [review]
good

**Review by simk2020 — COMMENTED** [review]
ok

**Comment by TylerSilverman** [comment]
edit the style and added route functions

**Review by TylerSilverman — COMMENTED** [review]
edit the style and added route functions

**Review by simk2020 — APPROVED** [review]
good

**Pull request merged**
